### ISSUE TITLE
FEAT: Add UIUCTF write up 

### ISSUE THREAD

**Issue by Mathis-Dory** [dothidden/writeups#48]
Hey guys do not forget to add your write up, here again we can earn some prizes but we only have 7 days to do it.

After merging this issue, you can send the writeup link to:  https://forms.gle/1MSh8X3LJtV7yn29A

**Comment by Stefan-Radu** [comment]
@Costinteo do you have anything left to add here? 
I pushed my writeups on branch #48 [uiuctf](https://github.com/dothidden/writeups/tree/48-feat-add-uiuctf-write-up).

**Comment by Costinteo** [comment]
I don't.
