### ISSUE TITLE
FEAT: Add the writeup for Dante CTF

### ISSUE THREAD

**Issue by Mathis-Dory** [dothidden/writeups#7]
# Add a new page for all challs of Dante CTF

- Add your writeup with the correct tags
- Add the new Dante section
- Add our ranking

https://dantectf.it

**Comment by Costinteo** [comment]
I will add a writeup for soulcode.

**Comment by Mathis-Dory** [comment]
> I will add a writeup for soulcode today. And the initial page.

Initial page is already pushed :)

**Comment by Costinteo** [comment]
> I've also got quite a few that I'd like to add

@Stefan-Radu branch off from Mathis' branch and pull request to it, like I did. I think it's pretty clean this way.
